events { }
http {
    server {
        listen 80;
        server_name 158.160.239.74;

        location / {
            proxy_pass http://localhost:3000/;
        }

        location /api/ {
            proxy_pass http://localhost:8000/;
        }
    }
}